name: flutter_cached_pdfview
description: A package to show Native PDF View for iOS and Android, support Open from a different resource like Path, Asset or Url and Cache it.
version: 0.4.0-nullsafety
homepage: https://abdosaed.ml/
repository: https://github.com/AbdOoSaed/flutter_cached_pdfview
issue_tracker: https://github.com/AbdOoSaed/flutter_cached_pdfview/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
# new pubspec
#https://flutter.dev/docs/development/packages-and-plugins/developing-packages
dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.1.0
  flutter_cache_manager: ^3.0.0-nullsafety.1
  path_provider: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
